font:
  normal:
    family: "JetBrainsMono Nerd Font"
    style: Thin

  bold:
    family: "JetBrainsMono Nerd Font"
    style: Regular

  italic:
    family: "JetBrainsMono Nerd Font"
    style: Italic

  bold_italic:
    family: "JetBrainsMono Nerd Font"
    style: Bold Italic

  size: 25

window:
  dimensions:
    columns: 200
    lines: 85

  decorations: buttonless

  startup_mode: Maximized
  opacity: 1
  use_thin_strokes: true

colors:
  transparent_background_colors: true

key_bindings:
  - { key: Key3, mods: Alt, chars: "#" }
  - { key: D, mods: Command, chars: "\x02v" }
  - { key: D, mods: Command|Shift, chars: "\x02s" }
  - { key: Return, mods: Command, chars: "\x02v" }
  - { key: Return, mods: Command|Shift, chars: "\x02s" }
  - { key: T, mods: Command, chars: "\x02c" }
  - { key: W, mods: Command, chars: "\x02x" }
  - { key: H, mods: Command, chars: "\x02h" }
  - { key: J, mods: Command, chars: "\x02j" }
  - { key: K, mods: Command, chars: "\x02k" }
  - { key: L, mods: Command, chars: "\x02l" }
  - { key: LBracket, mods: Command, chars: "\x02h" }
  - { key: RBracket, mods: Command, chars: "\x02l" }
  - { key: F, mods: Command, chars: "\x02F" }
  - { key: Key1, mods: Command, chars: "\x021" }
  - { key: Key2, mods: Command, chars: "\x022" }
  - { key: Key3, mods: Command, chars: "\x023" }
  - { key: Key4, mods: Command, chars: "\x024" }
  - { key: Key5, mods: Command, chars: "\x025" }
  - { key: Key6, mods: Command, chars: "\x026" }
  - { key: Key7, mods: Command, chars: "\x027" }
  - { key: Key8, mods: Command, chars: "\x028" }
  - { key: Key9, mods: Command, chars: "\x029" }
  - { key: Left, mods: Command, chars: "\x02H" }
  - { key: Down, mods: Command, chars: "\x02J" }
  - { key: Right, mods: Command, chars: "\x02L" }
  - { key: Up, mods: Command, chars: "\x02K" }
